import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Bellefair&display=swap');
        </style>
      </Head>
      <body className={inter.className}>
        <Navbar />
        <div className="min-h-screen">{children}</div>
        <div>footer</div>
      </body>
    </html>
  );
}
